"""Hand-researched fish-health pages served as static overrides — 2026-09-28.

The species app renders ~8,000 /fish-health/ pages from glm-4-flash copy that
lists the same five causes for every species. Google's AI Overview for these
queries leads with the species-specific cause (a bloated guppy is usually
pregnant; a fading flowerhorn is usually the "fader" gene), and our template
pages miss it. blood-parrot-cichlid-pale-color, the one page rewritten by hand
with citations, is also the one with the most clicks.

This script runs a controlled test of that rewrite on the top pages by
impressions:

  select <gsc-export.xlsx>   pair the top 80 pages by impressions, assign one
                             of each pair to "test" at random
                             → reports/fish-health-deep-test-2026-09-28.csv
  fetch <slug>...            snapshot species facts, dates and links from the
                             species app (upstream, not the public URL, which
                             becomes our own page once the override is live)
                             → data-pipeline/fish_health_deep/<slug>.live.json
  check <slug>...            validate content files without writing anything
  render [<slug>...]         build fish-health/<slug>/index.html from
                             data-pipeline/fish_health_deep/<slug>.json and
                             regenerate the nginx override block

Content files hold the researched copy. Citations are written inline as [n]
and point at the page's own references list; <em> and <strong> are allowed.
"""

from __future__ import annotations

import argparse
import csv
import html
import json
import random
import re
import sys
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CONTENT = Path(__file__).resolve().parent / "fish_health_deep"
OUT = ROOT / "fish-health"
SHELL = OUT / "blood-parrot-cichlid-pale-color" / "index.html"
NGINX = ROOT / "nginx.conf"
REPORT = ROOT / "reports" / "fish-health-deep-test-2026-09-28.csv"
UPSTREAM = "https://fishcareai-species-app-b1e198.anysites.app/fish-health/"
SITE = "https://www.fishcareai.com"

SEED = 20260928
MAX_PAGES = 80
MAX_POSITION = 15.0
# Already served as static pages; not part of the test.
STATIC = {"blood-parrot-cichlid-pale-color", "celestial-pearl-danio-black-spots"}

NGINX_BEGIN = "    # BEGIN fish-health deep pages (generated by data-pipeline/fish_health_deep.py)\n"
NGINX_END = "    # END fish-health deep pages\n"
NGINX_ANCHOR = "    # ── Proxy: Species App"

LIKELIHOOD = {"high": ("likelihood-high", "Most Likely"),
              "medium": ("likelihood-medium", "Possible"),
              "low": ("likelihood-low", "Less Common")}
URGENCY_ICON = {"monitor": "🔍", "urgent": "⚠️", "emergency": "🚨"}


# ---------------------------------------------------------------- select

def select(export: Path) -> None:
    from openpyxl import load_workbook

    rows = list(load_workbook(export, read_only=True)["网页"].iter_rows(values_only=True))[1:]
    pages = []
    for url, clicks, impr, ctr, pos in rows:
        m = re.search(r"/fish-health/([a-z0-9-]+)$", url or "")
        if not m or m.group(1) in STATIC or m.group(1) == "fish" or pos > MAX_POSITION:
            continue
        pages.append({"slug": m.group(1), "url": url, "clicks": int(clicks), "impressions": int(impr),
                      "ctr": round(ctr * 100, 2), "position": round(pos, 2)})
    pages.sort(key=lambda r: -r["impressions"])
    pages = pages[:MAX_PAGES]

    rng = random.Random(SEED)
    for i in range(0, len(pages), 2):
        pair = pages[i:i + 2]
        rng.shuffle(pair)
        pair[0]["group"] = "test"
        if len(pair) > 1:
            pair[1]["group"] = "control"

    REPORT.parent.mkdir(parents=True, exist_ok=True)
    with REPORT.open("w", newline="", encoding="utf-8") as fh:
        w = csv.DictWriter(fh, fieldnames=["slug", "group", "impressions", "clicks", "ctr", "position", "url"])
        w.writeheader()
        w.writerows(sorted(pages, key=lambda r: (r["group"], -r["impressions"])))
    for g in ("test", "control"):
        rs = [r for r in pages if r["group"] == g]
        imp, clk = sum(r["impressions"] for r in rs), sum(r["clicks"] for r in rs)
        print(f"{g:8} pages={len(rs)} impressions={imp} clicks={clk} ctr={clk / imp * 100:.2f}% "
              f"avg_pos={sum(r['position'] for r in rs) / len(rs):.2f}")
    print(f"wrote {REPORT.relative_to(ROOT)}")


# ---------------------------------------------------------------- fetch

def _clean(fragment: str) -> str:
    return html.unescape(re.sub(r"<!-- -->|<[^>]+>", "", fragment)).strip()


def fetch(slugs: list[str]) -> None:
    CONTENT.mkdir(parents=True, exist_ok=True)
    for slug in slugs:
        req = urllib.request.Request(UPSTREAM + slug, headers={"User-Agent": "Mozilla/5.0"})
        page = urllib.request.urlopen(req, timeout=60).read().decode("utf-8")
        profile = dict(re.findall(r"<tr><td>([^<]+)</td><td[^>]*>(.*?)</td></tr>",
                                  re.search(r'<table class="qf-table">(.*?)</table>', page, re.S).group(1)))
        crumbs = re.findall(r'<a href="([^"]*)"[^>]*>([^<]*)</a>', re.search(r'class="breadcrumb">(.*?)</div>', page, re.S).group(1))
        guide = re.search(r'<a href="((?:https://www\.fishcareai\.com)?/guides/[^"]+)"[^>]*>([^<]+)</a>', page)
        live = {
            "slug": slug,
            "species": _clean(profile["Species"]),
            "scientific": _clean(profile["Scientific"]),
            "water": _clean(profile.get("Water", "")),
            "temp": _clean(profile.get("Temp", "")),
            "ph": _clean(profile.get("pH", "")),
            "care": _clean(profile.get("Care level", "")),
            "fish_hub": next(h for h, _ in crumbs if h.startswith("/fish-health/fish/")),
            "problem": _clean(re.search(r"Problem:</strong>(.*?)</div>", page, re.S).group(1)).replace("\xa0", " ").strip(),
            "category": _clean(re.search(r"Category:</strong>(.*?)</div>", page, re.S).group(1)).replace("\xa0", " ").strip(),
            "urgency": _clean(re.search(r"Urgency:</strong>(.*?)</div>", page, re.S).group(1)).replace("\xa0", " ").strip(),
            "hero": re.search(r'class="sp-hero-img" src="([^"]+)"', page).group(1),
            "species_profile": re.search(r'<a href="(/species/[^"]+)"', page).group(1),
            "guide": {"href": guide.group(1), "label": _clean(guide.group(2))} if guide else None,
            "date_published": re.search(r'"datePublished":"([^"]+)"', page).group(1),
        }
        (CONTENT / f"{slug}.live.json").write_text(json.dumps(live, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
        print(f"fetched {slug}: {live['species']} / {live['problem']} ({live['urgency']})")


# ---------------------------------------------------------------- render

def cite(text: str) -> str:
    """[3] or [2][3] → <sup class="cit"> links into the reference list."""
    def sup(m: re.Match) -> str:
        nums = re.findall(r"\[(\d+)\]", m.group(0))
        return '<sup class="cit">' + "".join(f'<a href="#ref-{n}">[{n}]</a>' for n in nums) + "</sup>"
    return re.sub(r"(?:\[\d+\])+", sup, text)


def plain(text: str) -> str:
    return re.sub(r"\s+", " ", re.sub(r"\[\d+\]|<[^>]+>", "", text)).strip()


def esc(text: str) -> str:
    return html.escape(text, quote=True)


def ld(obj: dict) -> str:
    return '<script type="application/ld+json">' + json.dumps(obj, ensure_ascii=False).replace("</", "<\\/") + "</script>"


def steps(items: list[dict]) -> str:
    out = []
    for i, s in enumerate(items, 1):
        tool = f'\n    <div class="step-tool">Recommended: {esc(s["tool"])}</div>' if s.get("tool") else ""
        out.append(f"""<li class="step-item">
  <div class="step-num" aria-hidden="true">{i}</div>
  <div class="step-body">
    <div class="step-action">{esc(s["action"])}</div>
    <p class="step-detail">{cite(s["detail"])}</p>{tool}
  </div>
</li>""")
    return '<ol class="steps-list">\n\n' + "\n\n".join(out) + "\n\n</ol>"


def sidebar_link(href: str, label: str, last: bool = False) -> str:
    return (f'  <div style="margin-bottom:{16 if last else 8}px">\n    <a href="{esc(href)}" style="display:block;text-align:center;'
            'padding:10px;background:var(--card-bg);border:1px solid var(--bd);border-radius:8px;font-size:0.84rem;'
            f'color:var(--p);font-weight:600">{label}</a>\n  </div>')


def render_page(c: dict, live: dict, shell: str) -> str:
    slug, url = c["slug"], f"{SITE}/fish-health/{c['slug']}"
    # A content file may correct species facts the app's database gets wrong.
    live = {**live, **c.get("species_overrides", {})}
    species, problem = live["species"], live["problem"]
    head_common = re.search(r'(<link rel="stylesheet" href="/assets/fish-health-static\.css[^>]*>)', shell).group(1)
    tail_script = re.search(r'(<script defer src="/assets/site-compliance\.js[^"]*"></script>)', shell).group(1)
    nav = shell[shell.index("<body>"):shell.index("<main>")]
    footer = shell[shell.index("</main>"):]
    img_alt = f"{species} — {problem}"

    breadcrumb = {"@context": "https://schema.org", "@type": "BreadcrumbList", "itemListElement": [
        {"@type": "ListItem", "position": 1, "name": "Home", "item": SITE},
        {"@type": "ListItem", "position": 2, "name": "Fish Health", "item": f"{SITE}/fish-health/"},
        {"@type": "ListItem", "position": 3, "name": species, "item": SITE + live["fish_hub"]},
        {"@type": "ListItem", "position": 4, "name": f"{species} {problem}", "item": url}]}
    article = {"@context": "https://schema.org", "@type": "Article", "headline": c["h1"], "description": c["description"],
               "url": url, "image": live["hero"], "datePublished": live["date_published"],
               "dateModified": c["date_modified"] + "T00:00:00.000Z",
               "author": {"@type": "Organization", "name": "FishCare AI Editorial Team"},
               "publisher": {"@type": "Organization", "name": "FishCare AI", "url": SITE},
               "about": {"@type": "Thing", "name": live["scientific"]}}
    howto = {"@context": "https://schema.org", "@type": "HowTo", "name": c["howto_name"], "description": c["description"],
             "step": [{"@type": "HowToStep", "name": f"[Diagnose] {s['action']}", "text": plain(s["detail"])} for s in c["diagnose"]]
                     + [{"@type": "HowToStep", "name": f"[Fix] {s['action']}", "text": plain(s["detail"])} for s in c["fix"]]}
    faq = {"@context": "https://schema.org", "@type": "FAQPage", "mainEntity": [
        {"@type": "Question", "name": f["q"], "acceptedAnswer": {"@type": "Answer", "text": plain(f["a"])}} for f in c["faq"]]}

    causes = []
    for cause in c["causes"]:
        cls, label = LIKELIHOOD[cause["likelihood"]]
        paras = "\n  ".join(f"<p>{cite(p)}</p>" for p in cause["paragraphs"])
        causes.append(f"""<div class="cause-card">
  <div class="cause-card-top">
    <h4>{esc(cause["title"])}</h4>
    <span class="likelihood-badge {cls}">{label}</span>
  </div>
  {paras}
</div>""")

    faqs = "\n\n".join(f"""<details class="fqi">
  <summary class="fqq">{esc(f["q"])}</summary>
  <div class="fqa">{cite(f["a"])}</div>
</details>""" for f in c["faq"])

    refs = "\n".join(
        f'  <li id="ref-{i}">{r["authors"]} <cite>{r["title"]}</cite> {r["source"]} '
        f'<a href="{esc(r["url"])}" rel="nofollow noopener" target="_blank">{esc(r["label"])}</a></li>'
        for i, r in enumerate(c["references"], 1))

    links = []
    if live.get("guide"):
        links.append(sidebar_link(live["guide"]["href"], "🐟 " + esc(live["guide"]["label"].lstrip("🐟 ").strip())))
    links.append(sidebar_link(live["species_profile"], "📖 View Species Profile"))
    links.append(sidebar_link(live["fish_hub"], f"🩺 All {esc(species)} Health Problems"))
    links.append(sidebar_link("/fish-health/", "🐠 Fish Health Hub", last=True))

    intro = "\n\n".join(f'<p style="font-size:1rem;line-height:1.8">{cite(p)}</p>' for p in c["intro"])
    quick = (f'<div class="callout callout-ok" style="margin-top:0"><strong>Short answer:</strong> {cite(c["short_answer"])}</div>\n\n'
             if c.get("short_answer") else "")

    return f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>{esc(c["title"])}</title>
<meta name="description" content="{esc(c["description"])}">
<meta name="robots" content="index,follow,max-image-preview:large,max-snippet:-1,max-video-preview:-1">
<link rel="canonical" href="{url}">
{head_common}

<meta property="og:type" content="article">
<meta property="og:title" content="{esc(c["h1"])}">
<meta property="og:description" content="{esc(c["description"])}">
<meta property="og:url" content="{url}">
<meta property="og:site_name" content="FishCare AI">
<meta property="og:image" content="{live["hero"]}">
<meta property="og:image:width" content="1280">
<meta property="og:image:height" content="640">
<meta property="og:image:alt" content="{esc(img_alt)}">
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:title" content="{esc(c["h1"])}">
<meta name="twitter:description" content="{esc(c["description"])}">
<meta name="twitter:image" content="{live["hero"]}">
<meta name="twitter:image:alt" content="{esc(img_alt)}">

{ld(breadcrumb)}
{ld(article)}
{ld(howto)}
{ld(faq)}
{tail_script}</head>
{nav}<main>

<section class="sp-hero">
  <img class="sp-hero-img" src="{live["hero"]}" alt="{esc(img_alt)}" width="1280" height="340" fetchpriority="high" decoding="async">
  <div class="sp-hero-overlay"></div>
  <div class="sp-hero-inner">
    <div class="breadcrumb">
      <a href="{SITE}">Home</a>
      <span>/</span>
      <a href="/fish-health/">Fish Health</a>
      <span>/</span>
      <a href="{live["fish_hub"]}">{esc(species)}</a>
      <span>/</span>
      <span style="color:rgba(255,255,255,.85)">{esc(problem)}</span>
    </div>
    <div class="sp-tag" style="text-transform:capitalize">{URGENCY_ICON.get(c["urgency"], "🔍")} {esc(c["urgency"].capitalize())} · {esc(live["category"])}</div>
    <h1>{esc(c["h1"])}</h1>
    <div class="sci-name">{esc(live["scientific"])}</div>
    <div class="sp-meta-row">
      <div class="sp-meta-item">🐟 <strong>Species:</strong>&nbsp;{esc(species)}</div>
      <div class="sp-meta-item">🔬 <strong>Problem:</strong>&nbsp;{esc(problem)}</div>
      <div class="sp-meta-item" style="text-transform:capitalize">📋 <strong>Category:</strong>&nbsp;{esc(live["category"])}</div>
      <div class="sp-meta-item" style="text-transform:capitalize">⚡ <strong>Urgency:</strong>&nbsp;{esc(c["urgency"])}</div>
    </div>
    <p style="color:rgba(255,255,255,.7);font-size:.82rem;margin-top:10px">Updated {esc(c["date_modified_human"])} · FishCare AI Editorial Team</p>
  </div>
</section>

<div class="con">
<div class="sp-layout">

<article class="artc" id="article">

{quick}{intro}

<h2 id="causes">{esc(c["causes_h2"])}</h2>

<div class="causes-grid">

{chr(10).join(causes)}

</div>

<h2 id="diagnose">{esc(c["diagnose_h2"])}</h2>

<p>{cite(c["diagnose_intro"])}</p>

{steps(c["diagnose"])}

<h2 id="fix">{esc(c["fix_h2"])}</h2>

{steps(c["fix"])}

<h2 id="prevention">{esc(c["prevention_h2"])}</h2>

<div class="callout callout-ok">
{cite(c["prevention"])}</div>

<h2 id="seek-help">{esc(c["seek_help_h2"])}</h2>

<div class="callout callout-warn">
{cite(c["seek_help"])}</div>

<div class="cta-box" style="background:linear-gradient(135deg,#0F3D5E,#2E9E7D);margin-top:0">
  <h4>🔬 AI Symptom Checker</h4>
  <p>Not sure what's wrong? Describe your fish's symptoms to the FishCare AI symptom checker for a second opinion before you treat.</p>
  <a class="btn" href="{SITE}/#symptom-checker">Check Symptoms →</a>
</div>

<h2 id="faq">Frequently Asked Questions</h2>

{faqs}

<div class="abox" style="margin-top:32px">
  <div class="aav">✓</div>
  <div>
    <strong>Editorial review</strong>
    <p>This guide was researched against the veterinary and scientific sources listed below and reviewed for biological accuracy. Test water parameters before treating a sick fish, and consult an aquatic veterinarian if symptoms persist after 48 hours of correct treatment.</p>
  </div>
</div>

<h2 id="references">References</h2>
<ol class="reflist">
{refs}
</ol>

</article>

<aside class="sp-sidebar">
  <div class="qf-card">
    <div class="qf-head">Fish Profile</div>
    <table class="qf-table">
      <tbody>
        <tr><td>Species</td><td>{esc(species)}</td></tr>
        <tr><td>Scientific</td><td><em>{esc(live["scientific"])}</em></td></tr>
        <tr><td>Water</td><td style="text-transform:capitalize">{esc(live["water"])}</td></tr>
        <tr><td>Temp</td><td>{esc(live["temp"])}</td></tr>
        <tr><td>pH</td><td>{esc(live["ph"])}</td></tr>
        <tr><td>Care level</td><td style="text-transform:capitalize">{esc(live["care"])}</td></tr>
      </tbody>
    </table>
  </div>

{chr(10).join(links)}

  <div class="toc-card">
    <h4>Contents</h4>
    <a href="#causes">Common Causes</a>
    <a href="#diagnose">How to Diagnose</a>
    <a href="#fix">How to Fix</a>
    <a href="#prevention">Prevention</a>
    <a href="#seek-help">When to Seek Help</a>
    <a href="#faq">FAQ</a>
    <a href="#references">References</a>
  </div>
</aside>

</div>
</div>

{footer}"""


def check(c: dict) -> list[str]:
    """Every [n] must resolve to a reference and every reference must be cited."""
    blob = json.dumps({k: v for k, v in c.items() if k != "references"}, ensure_ascii=False)
    used = {int(n) for n in re.findall(r"\[(\d+)\]", blob)}
    n = len(c["references"])
    problems = [f"cites [{u}] but only {n} references" for u in sorted(used) if u > n]
    problems += [f"reference {i} never cited" for i in range(1, n + 1) if i not in used]
    if len(c["title"]) > 60:
        problems.append(f"title {len(c['title'])} chars")
    if len(c["description"]) > 160:
        problems.append(f"description {len(c['description'])} chars")
    return problems


def update_nginx(slugs: list[str]) -> None:
    conf = NGINX.read_text(encoding="utf-8")
    block = NGINX_BEGIN + "".join(
        f"    location = /fish-health/{s} {{\n        try_files /fish-health/{s}/index.html =404;\n    }}\n"
        for s in sorted(slugs)) + NGINX_END
    if NGINX_BEGIN in conf:
        conf = conf[:conf.index(NGINX_BEGIN)] + block + conf[conf.index(NGINX_END) + len(NGINX_END):]
    else:
        conf = conf.replace(NGINX_ANCHOR, block + "\n" + NGINX_ANCHOR, 1)
    NGINX.write_text(conf, encoding="utf-8")


def render(only: list[str]) -> None:
    shell = SHELL.read_text(encoding="utf-8")
    files = sorted(p for p in CONTENT.glob("*.json") if not p.name.endswith(".live.json"))
    rendered, failed = [], False
    for f in files:
        c = json.loads(f.read_text(encoding="utf-8"))
        slug = c["slug"]
        problems = check(c)
        if problems:
            failed = True
            print(f"✗ {slug}: " + "; ".join(problems))
            continue
        if only and slug not in only:
            # Keep routing pages rendered earlier; never route to a page that has no HTML yet.
            if (OUT / slug / "index.html").exists():
                rendered.append(slug)
            continue
        rendered.append(slug)
        live = json.loads((CONTENT / f"{slug}.live.json").read_text(encoding="utf-8"))
        (OUT / slug).mkdir(parents=True, exist_ok=True)
        (OUT / slug / "index.html").write_text(render_page(c, live, shell), encoding="utf-8")
        words = len(plain(" ".join(json.dumps(c, ensure_ascii=False).split())).split())
        print(f"✓ {slug} (~{words} words, {len(c['references'])} refs)")
    update_nginx(rendered)
    if failed:
        sys.exit(1)


def main() -> None:
    ap = argparse.ArgumentParser()
    sub = ap.add_subparsers(dest="cmd", required=True)
    sub.add_parser("select").add_argument("export", type=Path)
    sub.add_parser("fetch").add_argument("slugs", nargs="+")
    sub.add_parser("render").add_argument("slugs", nargs="*")
    sub.add_parser("check").add_argument("slugs", nargs="+")
    args = ap.parse_args()
    if args.cmd == "check":
        bad = False
        for slug in args.slugs:
            c = json.loads((CONTENT / f"{slug}.json").read_text(encoding="utf-8"))
            problems = check(c)
            words = len(plain(json.dumps(c, ensure_ascii=False)).split())
            print(("✗ " if problems else "✓ ") + f"{slug} (~{words} words, {len(c['references'])} refs) " + "; ".join(problems))
            bad |= bool(problems)
        sys.exit(1 if bad else 0)
    if args.cmd == "select":
        select(args.export)
    elif args.cmd == "fetch":
        fetch(args.slugs)
    else:
        render(args.slugs)


if __name__ == "__main__":
    main()
