"""
generate_koi_special_pairs.py
─────────────────────────────
Two koi pair pages the main compatibility generator cannot produce, because
neither partner is one of its 91 catalogued aquarium fish:

  /compatibility/koi-and-turtles/   "koi and turtles"
  /compatibility/koi-and-pleco/     "koi and pleco"

Both keywords previously resolved to /guides/koi-fish-care/tank-mates/, which
answers them in a section rather than under the title. These pages put the
verdict and the compatibility score directly beneath the H1 and in the opening
paragraph, matching every other pair page on the site.

The scores come from the site's own model (generate_compatibility_pages_v2.
enhanced_compat) applied to the two profiles defined below, so they are
comparable with the generated pages rather than invented separately.

Turtles are held to the same "aggressive, eats small tank mates" treatment the
model gives predatory fish; plecos are tropical, so koi + pleco scores 0 for
the same coldwater/tropical reason as the existing bristlenose-pleco-and-koi
page.

These two pages are NOT regenerated by generate_compatibility_pages_v2.py
(its catalogue asserts exactly 91 species). Re-running that script leaves them
in place but drops them from sitemap.xml, so re-add them if that happens.

Run:  python3 generate_koi_special_pairs.py
"""

from pathlib import Path

import generate_compatibility_pages as v1
import generate_compatibility_pages_v2 as v2

ROOT = Path(__file__).resolve().parent.parent

EXTRA_SPECIES = {
    "turtles": {
        "name": "Turtles",
        "sci": "Trachemys scripta elegans and relatives",
        # Slider-type pond turtles: basking species kept in 68-85F water.
        "temp_min": 68, "temp_max": 85,
        "ph_min": 6.0, "ph_max": 8.0,
        "temperament": "aggressive",
        "size": 10,                 # 8-12 in carapace for an adult slider
        "care": "advanced",
        "water": "coldwater",       # same freshwater system type as koi
        "min_group": 1, "diet": "omnivore", "eats_small": True,
        "zone": "top",              # surface breathers and baskers
        "min_tank_gal": 100,
        "wiki": "/guides/koi-fish-care/tank-mates/",
        "desc": "Aquatic basking reptiles kept in ponds and large tanks. Opportunistic "
                "carnivores that bite fins and tails, eat pond plants, and add a heavy "
                "waste load to the filtration system.",
    },
    "pleco": {
        "name": "Plecos",
        "sci": "Hypostomus plecostomus and relatives",
        "temp_min": 74, "temp_max": 80,
        "ph_min": 6.5, "ph_max": 7.8,
        "temperament": "semi",
        "size": 18,
        "care": "intermediate",
        "water": "freshwater",      # tropical, unlike the koi's coldwater
        "min_group": 1, "diet": "omnivore", "eats_small": False,
        "zone": "bottom",
        "min_tank_gal": 125,
        "wiki": "/guides/pleco-care-guide/",
        "desc": "Tropical South American suckermouth catfish that reach 18 inches and "
                "need 74-80F. Large species are known to rasp at the slime coat of big, "
                "slow-moving fish.",
    },
}

EXTRA_INCOMPATIBLE = [
    ("koi", "turtles",
     "Turtles bite koi fins and tails and will take smaller koi outright; the wounds "
     "left behind routinely turn into bacterial ulcers."),
]

EXTRA_CAUTION = [
    ("koi", "pleco",
     "Large plecos rasp at the slime coat of big, slow-moving fish, and a koi is exactly "
     "that target profile."),
]

PAIRS = [("koi", "turtles"), ("koi", "pleco")]

# The template's verdict paragraph is generic boilerplate ("one or both fish may
# suffer harm"), which reads wrong for a turtle and answers neither query
# directly. These replace it with the actual answer in the opening line.
DIRECT_ANSWER = {
    "koi-and-turtles": (
        "<p><strong>No \u2014 keep turtles and koi in separate systems.</strong> Slider-type "
        "turtles are opportunistic carnivores, and a pond of slow-moving, long-finned fish is "
        "exactly what they act on: they bite fins and tails, take koi small enough to swallow, "
        "and leave wounds that turn into bacterial ulcers even when the fish survives the bite. "
        "The pairing also fails on husbandry \u2014 turtles produce a heavy waste load, graze pond "
        "plants down to the roots, and need basking access a koi pond is not built to provide. "
        "A juvenile turtle may coexist with large koi for a season; that is a delay, not "
        "compatibility. Scored 18/100 on temperament and predation risk rather than water "
        "chemistry, which is the one thing the two do share.</p>"
        "<p>See the <a href=\"/guides/koi-fish-care/tank-mates/#turtles\">koi tank mates guide</a> "
        "for the species that do work in a koi pond.</p>"
    ),
    "koi-and-pleco": (
        "<p><strong>No \u2014 not in a pond, and only as a short-term compromise indoors.</strong> "
        "Plecos are tropical South American catfish that need 74\u201380\u00b0F, while koi do best at "
        "50\u201375\u00b0F. The single degree of overlap is not a shared range, and a pleco will not "
        "survive an outdoor pond winter in any temperate climate \u2014 which is why this pair scores "
        "0/100, the same as every other koi and tropical-fish combination on this site. In a "
        "heated indoor tank a second problem appears: large common plecos rasp at the slime coat "
        "of big, slow-moving fish, and a koi is exactly that target profile.</p>"
        "<p>If you want an indoor algae eater alongside juvenile koi, a "
        "<a href=\"/compatibility/bristlenose-pleco-and-koi/\">bristlenose pleco</a> stays under 5 "
        "inches and rarely rasps at fish \u2014 still a temperature compromise, and the koi still need "
        "to move to a pond. For pond algae, use filtration, shade and a UV clarifier rather than a "
        "fish; see the <a href=\"/guides/koi-fish-care/tank-mates/#pleco\">koi tank mates guide</a>.</p>"
    ),
}

UPDATED = "Updated September 9, 2026"



def koi_related_guides(sa, sb):
    """Only suggest pairs built around the catalogued species (koi).

    v2.related_guides walks both partners, which would emit links such as
    /compatibility/pleco-and-guppy/ that do not exist.
    """
    catalogued = sb if sa in EXTRA_SPECIES else sa
    selected = []
    candidates = []
    for other in v1.SPECIES:
        if other in (sa, sb) or other in EXTRA_SPECIES:
            continue
        pair = "-and-".join(sorted((catalogued, other)))
        result = v2.enhanced_compat(catalogued, other)
        candidates.append((v2.POPULARITY.get(other, 35), result["score"], pair, other))
    candidates.sort(key=lambda row: (-row[0], -row[1], row[2]))
    for _, _, pair, other in candidates[:6]:
        selected.append((pair, f"{v1.SPECIES[catalogued]['name']} + {v1.SPECIES[other]['name']}"))
    return selected


def swap_opening(page, pair_slug):
    """Replace the boilerplate verdict paragraph with a direct answer."""
    marker = "<h2>Compatibility Overview</h2>\n      "
    start = page.index(marker) + len(marker)
    end = page.index("</p>", start) + len("</p>")
    page = page[:start] + DIRECT_ANSWER[pair_slug] + page[end:]
    return page.replace("Updated August 18, 2026", UPDATED)


def main():
    # v2.load_catalogue() needs data-pipeline/output/08_raw.json, which is not in
    # the repo, so work from v1's built-in catalogue and apply the same two
    # defaults load_catalogue() would have filled in.
    v1.SPECIES.update(EXTRA_SPECIES)
    for fish in v1.SPECIES.values():
        fish.setdefault("zone", "mid")
        fish.setdefault("min_tank_gal", v1.min_tank_size(fish, fish))
    v1.SPECIAL_INCOMPATIBLE_PAIRS.extend(EXTRA_INCOMPATIBLE)
    v1.CAUTION_PAIRS.extend(EXTRA_CAUTION)
    v1.compute_compat = v2.enhanced_compat
    v2.related_guides = koi_related_guides

    for sa, sb in PAIRS:
        sa, sb = sorted((sa, sb))
        result = v2.enhanced_compat(sa, sb)
        page = v2.inject_v2(v1.make_page(sa, sb), sa, sb, result)
        page = swap_opening(page, f"{sa}-and-{sb}")
        out = ROOT / "compatibility" / f"{sa}-and-{sb}" / "index.html"
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(page, encoding="utf-8")
        print(f"✓ /compatibility/{sa}-and-{sb}/  "
              f"{result['score']}/100 {v1.VERDICT_TEXT[result['verdict']]}  "
              f"({len(page):,} bytes)")


if __name__ == "__main__":
    main()
