"""Build reviewed goldfish topic pages and keyword coverage preview. No network calls."""
from pathlib import Path
import json,html,re,xml.etree.ElementTree as ET
R=Path(__file__).resolve().parent.parent
DATA=json.loads((R/'data-pipeline/goldfish-cluster.json').read_text()); pages=DATA['pages']; rows=DATA['coverage']
B='/guides/goldfish-care/'; D='https://www.fishcareai.com'; IMG='/assets/encyclopedia/real/goldfish-wikimedia-real.jpg'; DATE='2026-09-09'
e=html.escape
CSS='''*{box-sizing:border-box}body{margin:0;background:#f1f7fb;color:#20394b;font:17px/1.75 system-ui,sans-serif}a{color:#17658a;text-underline-offset:3px}a:focus-visible,summary:focus-visible{outline:3px solid #b97514;outline-offset:4px}.nav{display:flex;flex-wrap:wrap;gap:24px;padding:18px max(24px,calc((100vw - 1180px)/2));background:white}.brand{font-weight:800;margin-right:auto}.hero{background:#123d52;color:white}.hero-inner{max-width:1180px;margin:auto;display:grid;grid-template-columns:1.35fr 1fr;align-items:center;gap:40px;padding:48px 24px}.hero img{width:100%;height:270px;object-fit:cover;border-radius:20px}.hero a{color:#c3e9f8}.eyebrow{color:#b2d7e7;letter-spacing:.13em;font-size:12px;text-transform:uppercase}h1{font-size:clamp(30px,4vw,48px);line-height:1.15;margin:18px 0}h2{font-size:26px;line-height:1.3;margin:0 0 16px}h3{line-height:1.35}.layout{max-width:1180px;margin:32px auto;display:grid;grid-template-columns:minmax(0,1fr) 280px;gap:28px;padding:0 24px}article,aside{min-width:0}section,.card{background:white;border:1px solid #d7e5ed;border-radius:16px;padding:28px;margin-bottom:20px}section{scroll-margin-top:20px}p{margin:0 0 14px}p:last-child{margin:0}.toc a{display:block;padding:7px 0;font-size:15px}.meta{font-size:13px;color:#597589}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(230px,1fr));gap:12px}.grid a{padding:16px;border:1px solid #d7e5ed;border-radius:10px;background:#fff}.table-wrap{overflow:auto}table{border-collapse:collapse;width:100%;font-size:15px}th,td{padding:14px;text-align:left;border-bottom:1px solid #d7e5ed;vertical-align:top}th{background:#edf5f9}summary{cursor:pointer;font-weight:700}footer{padding:32px 24px;text-align:center;background:#dfeef5}.skip{position:absolute;left:-9999px}.skip:focus{left:20px;top:10px;background:white;padding:10px;z-index:5}@media(max-width:760px){.hero-inner,.layout{grid-template-columns:1fr}.hero-inner{padding:28px 20px;gap:18px}.hero img{height:210px}.layout{padding:0 16px;gap:0}section,.card{padding:22px}.nav{padding:14px 20px;gap:15px}aside{order:-1}.cluster{display:none}h2{font-size:23px}}'''
(R/'assets/goldfish-cluster.css').write_text(CSS)
nav=''.join(f'<a href="{B}{x["slug"]}/">{e(x["title"])}</a>' for x in pages)
sources=[('UFAW: goldfish variety welfare','https://www.ufaw.org.uk/fish/fish'),('Aquarium Industries: goldfish facts','https://www.aquariumindustries.com.au/wp-content/uploads/2015/03/Goldfish.pdf'),('RSPCA: goldfish care','https://kb.rspca.org.au/categories/companion-animals/fish/how-should-i-care-for-my-goldfish'),('Merck Veterinary Manual: fish disorders','https://www.merckvetmanual.com/all-other-pets/fish/disorders-and-diseases-of-fish'),('PetMD: buoyancy disorders','https://www.petmd.com/fish/conditions/respiratory/swim-bladder-disorders-fish')]
for x in pages:
 url=B+x['slug']+'/'; title=x['title']; desc=x['desc']; faq=x['faq']
 schema=[{'@context':'https://schema.org','@type':'Article','headline':title,'description':desc,'image':D+IMG,'datePublished':DATE,'dateModified':DATE,'author':{'@type':'Organization','name':'FishCare AI Editorial Team','url':D+'/editorial-policy/'},'publisher':{'@type':'Organization','name':'FishCare AI','url':D},'mainEntityOfPage':D+url},{'@context':'https://schema.org','@type':'BreadcrumbList','itemListElement':[{'@type':'ListItem','position':i+1,'name':n,'item':D+u} for i,(n,u) in enumerate([('Home','/'),('Goldfish care',B),(title,url)])]},{'@context':'https://schema.org','@type':'FAQPage','mainEntity':[{'@type':'Question','name':faq[0],'acceptedAnswer':{'@type':'Answer','text':faq[1]}}]}]
 body=''.join(f'<section id="{sid}"><h2>{e(h)}</h2>{content}</section>' for sid,h,content in x['sections'])
 toc=''.join(f'<a href="#{sid}">{e(h)}</a>' for sid,h,_ in x['sections'])
 document=f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{e(title)}</title><meta name="description" content="{e(desc)}"><meta name="robots" content="index,follow,max-image-preview:large"><link rel="canonical" href="{D+url}"><link rel="icon" href="/favicon.svg"><link rel="stylesheet" href="/assets/goldfish-cluster.css"><meta property="og:type" content="article"><meta property="og:title" content="{e(title)}"><meta property="og:description" content="{e(desc)}"><meta property="og:url" content="{D+url}"><meta property="og:image" content="{D+IMG}"><meta name="twitter:card" content="summary_large_image"><meta name="twitter:title" content="{e(title)}"><meta name="twitter:description" content="{e(desc)}"><meta name="twitter:image" content="{D+IMG}">{''.join('<script type="application/ld+json">'+json.dumps(s)+'</script>' for s in schema)}</head><body><a class="skip" href="#main">Skip to content</a><nav class="nav" aria-label="Main"><a class="brand" href="/">FishCare AI</a><a href="/guides/">Care guides</a><a href="/tools/">Aquarium tools</a><a href="{B}">Goldfish</a></nav><header class="hero"><div class="hero-inner"><div><nav aria-label="Breadcrumb"><a href="/">Home</a> / <a href="{B}">Goldfish care</a></nav><p class="eyebrow">The goldfish care library</p><h1>{e(title)}</h1><p>{e(desc)}</p></div><img src="{IMG}" width="720" height="480" alt="Goldfish swimming in an aquarium" fetchpriority="high"></div></header><main id="main" class="layout"><article><p class="meta">FishCare AI Editorial Team · Updated <time datetime="{DATE}">September 9, 2026</time> · <a href="/editorial-policy/">Editorial policy</a></p>{body}<section id="faq"><h2>Frequently asked question</h2><details open><summary>{e(faq[0])}</summary><p>{e(faq[1])}</p></details></section><section id="sources"><h2>Sources and further reading</h2><p>General husbandry and health references. Individual fish and local conditions vary.</p><ul>{''.join(f'<li><a href="{u}">{e(n)}</a></li>' for n,u in sources)}</ul><p class="meta">See <a href="/image-credits/">image credits</a>.</p></section><section><h2>Continue your goldfish care plan</h2><div class="grid"><a href="{B}">Complete goldfish care guide</a><a href="{B}water-parameters/">Check water parameters</a><a href="/calculators/goldfish-tank-size/">Calculate tank size</a><a href="/aquarium-fish-diseases/goldfish-diseases/">Disease and symptom directory</a></div></section></article><aside><details class="card toc" open><summary>On this page</summary>{toc}<a href="#faq">Frequently asked question</a><a href="#sources">Sources</a></details><div class="card toc cluster"><h2>Explore goldfish</h2>{nav}</div></aside></main><footer>FishCare AI · <a href="/about/">About</a> · <a href="/editorial-policy/">Editorial policy</a> · <a href="/privacy/">Privacy</a></footer></body></html>'''
 dest=R/url.strip('/')/'index.html';dest.parent.mkdir(parents=True,exist_ok=True);dest.write_text(document)
# Insert crawlable cross-links without replacing existing editorial content.
def block(path,body):
 f=R/path; text=f.read_text(); text=re.sub(r'<!--goldfish-cluster:start-->.*?<!--goldfish-cluster:end-->','',text,flags=re.S)
 marker='<!--goldfish-cluster:start-->'+body+'<!--goldfish-cluster:end-->'
 anchor='</article>' if '</article>' in text else '</main>'
 if anchor not in text:anchor='</body>'
 text=text.replace(anchor,marker+anchor,1);f.write_text(text)
block('guides/goldfish-care/index.html','<section style="margin:28px auto;padding:24px;max-width:1100px" id="goldfish-topics"><h2>Explore the goldfish care library</h2><p>Detailed guides for each stage of keeping goldfish.</p><ul>'+''.join(f'<li><a href="{B}{x["slug"]}/">{e(x["title"])}</a></li>' for x in pages)+'</ul></section>')
health=pages[8:16]
block('aquarium-fish-diseases/goldfish-diseases/index.html','<section><h2>Goldfish symptoms: choose what you can observe</h2><p>Common goldfish diseases and parasites can share symptoms. Test water and oxygen before selecting treatment; gill flukes and ich require different assessments. Repeated rubbing or white spots alone cannot confirm a parasite.</p><ul>'+''.join(f'<li><a href="{B}{x["slug"]}/">{e(x["title"])}</a></li>' for x in health)+'</ul></section>')
block('compatibility/goldfish/index.html',f'<section><h2>Choosing the best tank mates for goldfish</h2><p>Start with goldfish of similar size and swimming ability. Check adult space, feeding access and temperature requirements for every companion.</p><p><a href="{B}tank-mate-groups/">Compare tetras, plecos, shrimp, snails, turtles, minnows and loaches</a>.</p></section>')
# Add sitemap entries, preserving unrelated URLs and metadata.
ns='http://www.sitemaps.org/schemas/sitemap/0.9'; ET.register_namespace('',ns)
f=R/'sitemaps/guides.xml'; root=ET.fromstring(f.read_text()); locs={el.find('{'+ns+'}loc').text:el for el in root if el.find('{'+ns+'}loc') is not None}
for url in [B]+[B+x['slug']+'/' for x in pages]:
 el=locs.get(D+url)
 if el is None:el=ET.SubElement(root,'{'+ns+'}url');ET.SubElement(el,'{'+ns+'}loc').text=D+url
 lm=el.find('{'+ns+'}lastmod')
 if lm is None:lm=ET.SubElement(el,'{'+ns+'}lastmod')
 lm.text=DATE
ET.indent(root);f.write_text(ET.tostring(root,encoding='unicode',xml_declaration=True))
# Non-indexable review page intentionally separate from public articles.
report=R/'reports/goldfish-seo';report.mkdir(parents=True,exist_ok=True)
(report/'coverage.json').write_text(json.dumps(rows,ensure_ascii=False,indent=2))
trs=''.join(f'<tr><td>{e(r["keyword"])}</td><td>{r["status"]}</td><td><a href="{r["url"]}">{r["url"]}</a></td><td>{r["note"]}</td></tr>' for r in rows)
(report/'index.html').write_text(f'<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>Goldfish 关键词覆盖与页面预览</title><link rel="stylesheet" href="/assets/goldfish-cluster.css"></head><body><main style="max-width:1250px;margin:40px auto;padding:24px"><h1>Goldfish 关键词覆盖与页面预览</h1><p>{len(rows)} 个关键词 · {sum(r["status"]=="已覆盖" for r in rows)} 个已覆盖 · {sum(r["status"]=="新建" for r in rows)} 个由 17 个新专题承接</p><p>以搜索意图聚合，不为同义词重复建页。已覆盖表示本地已有对应内容，不代表搜索排名或 Google 已收录。</p><p><a href="{B}">护理主页预览</a> · <a href="audit.json">页面检查结果</a></p><div class="table-wrap"><table><thead><tr><th>关键词</th><th>状态</th><th>页面预览</th><th>说明</th></tr></thead><tbody>{trs}</tbody></table></div></main></body></html>')
print(f'Generated {len(pages)} pages; mapped {len(rows)} keywords.')
