"""Content for the clownfish disease cluster (hub + species pages).

Every factual claim that is not general aquarium practice is tied to a key in
REFS; the species pages print the references they use.
"""

REFS = {
    "fa164": ("Yanong, R. P. E. <cite>Cryptocaryon irritans infections (marine white spot disease) in fish</cite>. University of Florida IFAS Extension, EDIS FA164.",
              "https://ask.ifas.ufl.edu/publication/FA164"),
    "fa165": ("Yanong, R. P. E. <cite>Use of copper in marine aquaculture and aquarium systems</cite>. University of Florida IFAS Extension, EDIS FA165 (revised 2024).",
              "https://ask.ifas.ufl.edu/publication/FA165"),
    "srac": ("Francis-Floyd, R. &amp; Floyd, M. R. <cite>Amyloodinium ocellatum, an important parasite of cultured marine fish</cite>. Southern Regional Aquaculture Center Publication No. 4705 (2011).",
             "https://thefishsite.com/articles/amyloodinium-ocellatum-an-important-parasite-of-cultured-marine-fish"),
    "blasiola": ("Blasiola, G. C. (1983). <cite>A review of Brooklynella parasitization in marine fishes: diagnosis, pathology and chemotherapy</cite>. IAAAM Proceedings.",
                 "https://www.vin.com/doc/?id=3863586"),
    "merck": ("Merck Veterinary Manual. <cite>Parasitic diseases of fish</cite>. Professional version.",
              "https://www.merckvetmanual.com/exotic-and-laboratory-animals/aquarium-fish/parasitic-diseases-of-fish"),
    "crosbie": ("Crosbie, P. B. B. &amp; Munday, B. L. (1999). <cite>Environmental factors and chemical agents affecting the growth of the pathogenic marine ciliate Uronema nigricans</cite>. Diseases of Aquatic Organisms 36: 213–219.",
                "https://www.int-res.com/abstracts/dao/v36/n3/p213-219/"),
    "cardoso": ("Cardoso, P. H. M. et al. (2019). <cite>Neobenedenia melleni (Monogenea: Capsalidae) in ornamental reef fish imported to Brazil</cite>. Revista Brasileira de Parasitologia Veterinária 28(1). doi:10.1590/S1984-296120180076",
                "https://doi.org/10.1590/S1984-296120180076"),
    "cheng": ("Cheng, et al. (2022). <cite>Lymphocystis disease virus infection in clownfish Amphiprion ocellaris and Amphiprion clarkii in Taiwan</cite>. Animals 13(1): 153. doi:10.3390/ani13010153",
              "https://doi.org/10.3390/ani13010153"),
    "ramudu": ("Ramudu, K. R. et al. (2017). <cite>Report on Amyloodinium spp. cysts infection in clownfish</cite>. Marine Fisheries Information Service, Technical &amp; Extension Series 234: 25–26. ICAR-CMFRI.",
               "https://eprints.cmfri.org.in/13061/"),
    "myopathy": ("IAAAM Proceedings. <cite>Case report of a non-infectious degenerative myopathy in captive-bred clownfish (Amphiprion clarkii)</cite>.",
                 "https://vin.com/doc/?id=9992624"),
}

# 30 legacy symptom slugs -> 8 sections. Also drives the nginx 301 map.
GROUPS = [
    ("breathing", "Breathing problems", "r", ["gasping", "rapid-breathing", "coughing"],
     "Fast gill movement, gasping at the surface or \"coughing\" (sudden flaring of the gills) is the most important sign on this page. Gill parasites — velvet, Brooklynella and flukes — attack the gills first, often before anything shows on the skin, and low oxygen or ammonia produce the same picture.",
     ["srac", "blasiola"]),
    ("skin", "Spots, slime and skin lesions", "a", ["white-spots", "black-spots", "spots-on-fins", "fuzzy-growth", "mucus-coating", "missing-scales", "red-streaks"],
     "Distinct salt-grain dots point to marine ich; a fine gold-grey dust to velvet; thick, peeling slime to Brooklynella. Red streaks and open sores are usually bacterial or Uronema infections taking hold after an injury. Firm, white, wart-like lumps on the body or fins fit lymphocystis, a virus documented in captive clownfish.",
     ["fa164", "srac", "blasiola", "cheng"]),
    ("appetite", "Not eating, bloating or a sunken belly", "a", ["not-eating", "sunken-belly", "bloated"],
     "Refusing food for a day or two after a move is normal. Refusing food in an established fish is often the first sign of a parasite. A swollen belly points to overfeeding, constipation or internal infection; a pinched, sunken belly to long-term underfeeding or internal parasites.",
     []),
    ("swimming", "Swimming sideways, sinking or floating", "a", ["swimming-sideways", "floating", "sinking", "curled-body", "darting", "jumping"],
     "Losing balance — floating, sinking, swimming sideways — usually means a swim bladder problem or an advanced infection. Darting and jumping are signs of irritation (parasites) or of being chased. A curved spine that develops over weeks can be nutritional or degenerative rather than infectious.",
     ["myopathy"]),
    ("eyes", "Cloudy or bulging eyes", "a", ["bulging-eyes", "cloudy-eyes"],
     "One cloudy or swollen eye is usually an injury. Both eyes together suggest infection, flukes or poor water quality. Corneal cloudiness was one of the first signs of skin flukes in imported reef fish.",
     ["cardoso"]),
    ("fins", "Torn, clamped or rotting fins", "a", ["fin-rot", "torn-fins", "clamped-fins"],
     "Clean tears are fight damage; ragged, whitish edges that keep receding are fin rot. Fins held tight to the body (clamped) are a general stress sign — check water quality before anything else.",
     []),
    ("behavior", "Hiding, lethargy, scratching or aggression", "g", ["hiding", "lethargic", "aggressive", "rubbing"],
     "Scratching on rock (\"flashing\") is an early parasite sign and deserves a close look under a flashlight. Hiding and lethargy are vague on their own; combine them with breathing and skin checks.",
     ["fa164"]),
    ("color", "Losing color or turning pale", "g", ["losing-color", "pale-color"],
     "Fading is a stress response — a new tank, bullying, unstable temperature or salinity. Pale color together with excess slime and fast breathing is the classic Brooklynella picture and is an emergency.",
     ["blasiola"]),
]

SPECIES = {
    "ocellaris": {
        "name": "Ocellaris", "full": "Ocellaris Clownfish", "latin": "Amphiprion ocellaris",
        "alias": "false percula, common clownfish",
        "slugs": ["ocellaris"],
        "img": "/assets/encyclopedia/real/ocellaris-clownfish-wikimedia-real.jpg",
        "img_alt": "Ocellaris clownfish (Amphiprion ocellaris)",
        "credit": ("Raimond Spekking", "CC BY-SA 4.0", "https://creativecommons.org/licenses/by-sa/4.0"),
        "size": "Up to about 11 cm (4.3 in)", "temper": "Peaceful for a clownfish", "source": "Mostly captive-bred",
        "risk": "Low with captive-bred fish; velvet and lymphocystis are documented in hatchery stock",
        "title": "Ocellaris Clownfish Diseases: Symptoms &amp; Treatment",
        "desc": "Ocellaris clownfish diseases by symptom — fast breathing, white spots, slime, not eating — with urgency, likely cause and safe quarantine treatment.",
        "answer": "Captive-bred ocellaris clownfish are among the hardiest marine fish, so most problems trace back to stress: a new tank, an uncycled quarantine, unstable salinity or a bullying tank mate. The diseases that do appear are the same marine parasites that affect other reef fish — marine ich, velvet and Brooklynella — plus lymphocystis, a virus that has been confirmed in ocellaris clownfish in breeding facilities.",
        "why": [
            "Ocellaris are the clownfish most people buy first, so they show up most often in beginners' tanks — where an uncycled system, overfeeding and skipped quarantine cause most illness.",
            "Being farmed does not make them immune. A hatchery report from ICAR-CMFRI found <em>Amyloodinium</em> (velvet) in three of eight captive ocellaris, and a 2022 study in Taiwan confirmed lymphocystis virus in ocellaris kept in a breeding room.",
            "The good news: a healthy, captive-bred ocellaris that eats well and lives in a stable tank rarely gets sick. Most cases follow a new arrival that was not quarantined.",
        ],
        "why_refs": ["ramudu", "cheng"],
        "notes": {
            "breathing": "In ocellaris, rapid breathing in the first two weeks after purchase is the main warning sign of velvet carried in from the shop.",
            "skin": "Raised white nodules that stay put for weeks fit lymphocystis, which Cheng et al. described in ocellaris as sparse, white, papilloma-like nodules on the body, gills and fins. It is unsightly but usually resolves with good water quality.",
            "appetite": "New ocellaris often hide and skip meals for 2–3 days. Offer small portions of frozen mysis or quality pellets twice a day and remove leftovers.",
            "swimming": "Young, fast-growing ocellaris fed large meals are prone to temporary buoyancy trouble. Fast 24 hours, then feed smaller portions.",
            "eyes": "Ocellaris pairs rarely fight hard enough to damage eyes, so cloudy eyes in both eyes deserve a closer look for flukes.",
            "fins": "Clamped fins in a single ocellaris are usually stress from a dominant tank mate — often the larger female of the pair.",
            "behavior": "The side-to-side \"wiggle\" near a favorite spot is normal ocellaris behavior, not a symptom.",
            "color": "Captive-bred ocellaris may look slightly duller than wild fish; that is genetics, not illness. Sudden fading is the warning sign.",
        },
        "treat": "Ocellaris tolerate a bare 10–20 gallon quarantine tank well. Their small size makes them easy to net for formalin baths, but they stress quickly when chased — use a cup or a second net. Keep a PVC pipe in the tank so they can hide.",
        "faq": [
            ("Are ocellaris clownfish prone to disease?", "No — captive-bred ocellaris are hardy. Most illness follows stress or a new, unquarantined fish. They can still catch marine ich, velvet and Brooklynella, and hatchery stock has been documented with velvet and lymphocystis."),
            ("What are the white bumps on my ocellaris clownfish?", "Firm white lumps that do not move or spread quickly may be lymphocystis, a virus reported in ocellaris clownfish. Tiny salt-grain dots that come and go are more likely marine ich."),
            ("Why is my new ocellaris clownfish not eating?", "Most new ocellaris start eating within 2–3 days. If it still refuses food after that and also breathes fast or shows spots, treat it as a parasite problem."),
        ],
    },
    "percula": {
        "name": "Percula", "full": "Percula Clownfish", "latin": "Amphiprion percula",
        "alias": "true percula, orange clownfish",
        "slugs": ["percula", "true-percula"],
        "img": "/assets/encyclopedia/real/true-percula-clownfish-wikimedia-real.jpg",
        "img_alt": "True percula clownfish (Amphiprion percula) with thick black bands",
        "credit": ("CrisisRose", "CC BY-SA 3.0", "https://creativecommons.org/licenses/by-sa/3.0"),
        "size": "Up to about 11 cm (4.3 in)", "temper": "Peaceful to moderately territorial", "source": "Captive-bred and wild",
        "risk": "Brooklynella has been confirmed in A. percula; wild-caught fish carry more parasites",
        "title": "Percula Clownfish Diseases: Symptoms &amp; Treatment",
        "desc": "Percula clownfish diseases, including true percula, by symptom — rapid breathing, slime, losing color — with urgency, cause and quarantine treatment.",
        "answer": "Percula — sold as \"true percula\" — get the same marine diseases as ocellaris, but wild-caught percula arrive with more parasites. Brooklynella, the slime-producing ciliate often called \"clownfish disease\", was confirmed in <em>Amphiprion percula</em> in Blasiola's review of outbreaks, and velvet and marine ich are the other fast-moving threats.",
        "why": [
            "\"Percula\" and \"true percula\" are the same species, <em>Amphiprion percula</em>. It differs from ocellaris by thicker black edging on the white bands and usually one fewer dorsal spine (9–10 rather than 10–11).",
            "Many percula in the trade are still wild-collected. Wild fish spend days in holding systems before sale, which is where Brooklynella and velvet spread; Blasiola lists <em>A. percula</em> among the anemonefish hosts of Brooklynella.",
            "Captive-bred percula are as hardy as ocellaris. If you can choose, buy captive-bred and quarantine anyway.",
        ],
        "why_refs": ["blasiola"],
        "notes": {
            "breathing": "Fast breathing with clear skin in a new percula is the early, gill-only stage of Brooklynella or velvet — both start on the gills.",
            "skin": "Patches of white slime that look like the fish is \"peeling\" are the textbook Brooklynella sign in percula. Start formalin the same day.",
            "appetite": "Wild-caught percula may not recognize pellets. Start with frozen mysis or brine shrimp enriched with vitamins, then mix in pellets.",
            "swimming": "Darting and jumping in a newly added percula often mean it is being chased; check the tank at lights-out.",
            "eyes": "Percula have a naturally orange iris; only clouding of the clear cornea over the eye is a symptom.",
            "fins": "Torn fins in percula usually come from a mismatched pair establishing which fish becomes female.",
            "behavior": "Percula can be more territorial than ocellaris, especially once paired. A fish that is chased and hides constantly needs to be separated.",
            "color": "Fading is one of the most common percula complaints. If it comes with slime or fast breathing, treat it as Brooklynella, not stress.",
        },
        "treat": "Treat percula in a separate hospital tank. For Brooklynella, Blasiola reported that formalin baths or prolonged formalin immersion worked, while copper at 0.15–0.20 mg/L did not eradicate it — so do not rely on copper alone if you see thick slime.",
        "faq": [
            ("Is a true percula the same as a percula clownfish?", "Yes. \"True percula\" is a trade name for Amphiprion percula, used to separate it from the ocellaris, which is sometimes sold as \"false percula\". The diseases and treatment are the same."),
            ("Why is my percula clownfish losing color?", "Usually stress from a move, bullying or unstable water. If the fading comes with thick slime or fast breathing, it may be Brooklynella, which needs formalin treatment the same day."),
            ("Do percula clownfish get Brooklynella?", "Yes. Brooklynella hostilis has been confirmed in Amphiprion percula, along with maroon and tomato clownfish, in published outbreak reports."),
        ],
    },
    "tomato": {
        "name": "Tomato", "full": "Tomato Clownfish", "latin": "Amphiprion frenatus",
        "alias": "red clownfish, bridled clownfish",
        "slugs": ["tomato"],
        "img": "/assets/encyclopedia/real/tomato-clownfish-wikimedia-real.jpg",
        "img_alt": "Tomato clownfish (Amphiprion frenatus) in a magnificent sea anemone",
        "credit": ("Diego Delso", "CC BY-SA 4.0", "https://creativecommons.org/licenses/by-sa/4.0"),
        "size": "Up to about 14 cm (5.5 in)", "temper": "Aggressive, especially females", "source": "Captive-bred and wild",
        "risk": "Fight injuries; Brooklynella documented in an importer outbreak",
        "title": "Tomato Clownfish Diseases: Symptoms &amp; Treatment",
        "desc": "Tomato clownfish diseases by symptom — gasping, fuzzy growth, missing scales, not eating — with urgency, likely cause and quarantine treatment.",
        "answer": "Tomato clownfish are tough but aggressive, so many of their health problems start as injuries — torn fins, missing scales and bite wounds that then become infected. They also get the classic marine parasites: Brooklynella was recorded in tomato clownfish during an importer outbreak described by Blasiola, and velvet and marine ich are just as dangerous for them as for smaller clowns.",
        "why": [
            "Tomato clownfish (<em>Amphiprion frenatus</em>) grow larger than ocellaris and females become strongly territorial. Fights with tank mates or a mismatched partner are the most common source of wounds.",
            "Wounds are the entry point for bacteria and for <em>Uronema</em>, a ciliate that eats into damaged skin. Treating the injury early prevents the infection.",
            "Blasiola describes a 1979 Brooklynella outbreak in tomato clownfish at an importer — a reminder that wild-caught tomatoes need a full quarantine.",
        ],
        "why_refs": ["blasiola", "crosbie"],
        "notes": {
            "breathing": "Tomatoes gasping at the surface together is more often an oxygen or temperature problem than disease — check the heater and aeration first.",
            "skin": "Missing scales and a white, fuzzy-looking edge around a wound mean infection is starting in an injury. Move the fish away from the aggressor and treat in quarantine.",
            "appetite": "A dominant tomato may block a subordinate from food. Watch feeding time before assuming disease.",
            "swimming": "Darting and jumping are common in tomatoes being chased by a female. A lid prevents jumping deaths.",
            "eyes": "Single cloudy eyes in tomatoes are usually bite or scrape injuries from rockwork during fights.",
            "fins": "Expect some fin nipping in a pair; ragged, receding edges that spread are fin rot.",
            "behavior": "Aggression is normal for a tomato. Constant hiding by a subordinate is not, and stress lowers resistance to parasites.",
            "color": "Juvenile tomatoes can show two or three white bars that fade to one head bar as they mature — that is normal color change, not disease.",
        },
        "treat": "Give tomatoes a 20 gallon or larger quarantine tank with several hiding pipes; they stress and bite in cramped tanks. Never quarantine two unpaired tomatoes together.",
        "faq": [
            ("Why is my tomato clownfish gasping?", "Check oxygen and temperature first: tomatoes gasping together usually means low oxygen. A single fish gasping with spots, dust or slime points to gill parasites such as velvet or Brooklynella."),
            ("What is the fuzzy growth on my tomato clownfish?", "A white, fuzzy edge around a wound is usually a bacterial infection starting in an injury. Separate the fish from the aggressor and treat in a hospital tank."),
            ("Are tomato clownfish hardy?", "Yes, but they are aggressive. Most of their health problems begin as fight injuries that become infected."),
        ],
    },
    "maroon": {
        "name": "Maroon", "full": "Maroon Clownfish", "latin": "Premnas biaculeatus",
        "alias": "spine-cheek anemonefish, gold stripe maroon",
        "slugs": ["maroon"],
        "img": "/assets/encyclopedia/real/maroon-clownfish-wikimedia-real.jpg",
        "img_alt": "Maroon clownfish (Premnas biaculeatus)",
        "credit": ("Nick Hobgood", "CC BY-SA 3.0", "https://creativecommons.org/licenses/by-sa/3.0"),
        "size": "Females up to about 17 cm (6.7 in)", "temper": "The most aggressive clownfish", "source": "Captive-bred and wild",
        "risk": "Fight injuries; listed as a Brooklynella host",
        "title": "Maroon Clownfish Diseases: Symptoms &amp; Treatment",
        "desc": "Maroon clownfish diseases by symptom — swimming sideways, torn fins, slime, not eating — with urgency, likely cause and quarantine treatment.",
        "answer": "Maroon clownfish are the largest and most aggressive clownfish, so torn fins, bite marks and stress from constant fighting cause many of the problems owners see. They are also a documented host of Brooklynella, the slime-producing parasite, and are just as vulnerable to velvet and marine ich as any reef fish.",
        "why": [
            "Maroons (<em>Premnas biaculeatus</em>) have traditionally been placed in their own genus, <em>Premnas</em>, and are recognizable by the spines on their cheeks. Females can reach about 17 cm and will fight other clownfish, their mate and even the owner's hand.",
            "Blasiola lists <em>Premnas biaculeatus</em> as one of the anemonefish hosts of Brooklynella.",
            "Because injuries are common, check a sick maroon for bite wounds before assuming a parasite — but never ignore fast breathing or slime.",
        ],
        "why_refs": ["blasiola"],
        "notes": {
            "breathing": "Maroons are big, high-oxygen fish. Rapid breathing in a crowded or warm tank may be oxygen, not disease.",
            "skin": "Bite wounds and torn skin heal well in clean water; red, spreading edges mean infection or Uronema has taken hold.",
            "appetite": "A maroon recovering from a fight may sulk and skip food for several days. Persistent refusal with other symptoms is a disease sign.",
            "swimming": "Swimming sideways after a fight can be injury or exhaustion. If it lasts more than a day, or the body starts to curve, isolate the fish.",
            "eyes": "Maroons often damage an eye on rockwork while fighting; one cloudy eye is usually trauma.",
            "fins": "Fin damage is expected in maroon pairs. Watch that it heals within two weeks.",
            "behavior": "Aggression is normal. A maroon that suddenly stops defending its territory is unwell.",
            "color": "Maroons darken with age and mood. Sudden pale patches with slime are the warning sign.",
        },
        "treat": "Use the largest quarantine tank you can — 30 gallons for an adult female maroon — and keep it alone. Maroons are strong and fast; plan how you will catch the fish before you start daily baths.",
        "faq": [
            ("Why is my maroon clownfish swimming sideways?", "After a fight it can be injury or exhaustion and usually passes within a day. If it continues, or the fish also breathes fast or stops eating, isolate it and look for infection or parasites."),
            ("Are maroon clownfish more prone to disease?", "Not inherently, but their aggression means more injuries, and injuries let infections in. They are also a documented Brooklynella host."),
            ("Can I treat my maroon clownfish in the display tank?", "Not for parasites. Copper and formalin harm invertebrates and corals, and parasites survive in a display that still has fish. Use a hospital tank."),
        ],
    },
}

DISEASES = [
    # name, latin, sign, speed level, speed text, treatment, refs
    ("Marine ich", "Cryptocaryon irritans", "White salt-grain spots, flashing, faster breathing", "a", "Days–weeks",
     "Copper at 0.15–0.20 mg/L free copper for at least 3–6 weeks, hyposalinity, or tank transfer", ["fa164"]),
    ("Marine velvet", "Amyloodinium ocellatum", "Fine gold-grey dust, very rapid breathing, hanging at the surface", "r", "Can kill in days",
     "Short freshwater dip for relief, then copper at 0.15–0.20 mg/L free copper", ["srac", "fa165"]),
    ("Brooklynella", "Brooklynella hostilis", "Thick white slime, peeling skin, pale color, rapid breathing", "r", "Can kill in days",
     "Formalin baths or prolonged formalin; copper did not eradicate it", ["blasiola"]),
    ("Uronema", "Uronema spp.", "Red ulcers that spread quickly, often from an injury", "a", "Days",
     "Formalin; formalin, malachite green and hydrogen peroxide were all effective in lab trials", ["crosbie"]),
    ("Flukes", "monogenean flatworms", "Flashing, cloudy eyes, heavy breathing, clear skin", "a", "Weeks",
     "Praziquantel baths — 2 mg/L given twice, four days apart, in one study", ["cardoso"]),
]
